import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { readdir, readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { parseFrontMatter } from '../utils/frontmatter'
import { RESPONSES_DIR } from '../utils/paths'
import { recordStat } from '../metrics'
import { loadState, updateState } from '../state'

const execFileAsync = promisify(execFile)

export interface PostInvestigationOptions {
  dryRun: boolean
  targetRepo: string
  labels: string[]
}

/**
 * Creates GitHub issues in the target repo for each investigation file.
 * Each issue includes the investigation analysis and the generated response.
 * Tracks posted investigations in state.json to avoid duplicates.
 */
export async function postInvestigationIssues(options: PostInvestigationOptions): Promise<void> {
  const repoDir = join(RESPONSES_DIR, 'github')
  let files: string[] = []
  try {
    files = await readdir(repoDir)
  } catch {
    return
  }

  const state = await loadState()
  const postedInvestigations: Record<string, string> = (state.meta?.postedInvestigations as Record<string, string>) ?? {}

  const investigationFiles = files.filter((f) => f.endsWith('-investigation.md'))

  for (const file of investigationFiles) {
    const fullPath = join(repoDir, file)
    const content = await readFile(fullPath, 'utf-8')
    const { meta, body: investigationBody } = parseFrontMatter(content)

    const issueNumber = Number(meta.issue_number)
    const repo = typeof meta.repo === 'string' ? meta.repo : ''
    if (!repo || !issueNumber) {
      console.warn(`Skipping investigation ${file}: missing repo or issue_number`)
      continue
    }

    // Build a unique key for deduplication
    const investigationKey = `${repo}#${issueNumber}`
    if (postedInvestigations[investigationKey]) {
      console.log(`Skipping investigation ${investigationKey}: already posted as ${options.targetRepo}#${postedInvestigations[investigationKey]}`)
      continue
    }

    // Try to find the corresponding response file
    const responseFileName = file.replace('-investigation.md', '.md')
    let responseBody = ''
    try {
      const responseContent = await readFile(join(repoDir, responseFileName), 'utf-8')
      const parsed = parseFrontMatter(responseContent)
      responseBody = parsed.body
    } catch {
      // No response file found -- investigation-only issue
    }

    // Extract source repo short name for labeling (e.g., "unity-builder" from "game-ci/unity-builder")
    const repoShortName = repo.split('/').pop() ?? repo

    // Build labels: always help-bot + investigation, plus source repo name
    const labels = [...options.labels]
    if (!labels.includes(repoShortName)) {
      labels.push(repoShortName)
    }

    // Build issue title
    const title = meta.title
      ? `[Investigation] ${repo}#${issueNumber}: ${meta.title}`
      : `[Investigation] ${repo}#${issueNumber}`

    // Build issue body
    const sourceUrl = `https://github.com/${repo}/issues/${issueNumber}`
    const sections: string[] = []

    sections.push(`> Investigation of ${sourceUrl}`)
    sections.push('')

    if (investigationBody) {
      sections.push('## Investigation')
      sections.push('')
      sections.push(investigationBody)
    }

    if (responseBody) {
      sections.push('')
      sections.push('---')
      sections.push('')
      sections.push('## Generated Response')
      sections.push('')
      sections.push('The following response was generated for the source issue:')
      sections.push('')
      sections.push(responseBody)
    }

    sections.push('')
    sections.push('---')
    sections.push(`*Generated by [GameCI Help Bot](https://github.com/game-ci/help-bot) | Source: ${sourceUrl}*`)

    const body = sections.join('\n')

    if (options.dryRun) {
      console.log(`DRY RUN: would create investigation issue in ${options.targetRepo}:`)
      console.log(`  Title: ${title}`)
      console.log(`  Labels: ${labels.join(', ')}`)
      console.log(`  Source: ${sourceUrl}`)
      recordStat('investigationIssuesSkipped', 1)
      continue
    }

    try {
      const labelArgs = labels.flatMap((l) => ['--label', l])
      const { stdout } = await execFileAsync('gh', [
        'issue', 'create',
        '--repo', options.targetRepo,
        '--title', title,
        ...labelArgs,
        '--body', body,
      ])
      const createdUrl = stdout.trim()
      const createdNumber = createdUrl.split('/').pop() ?? ''
      console.log(`Created investigation issue: ${createdUrl}`)

      // Track in state to avoid duplicates
      postedInvestigations[investigationKey] = createdNumber

      recordStat('investigationIssuesPosted', 1)
    } catch (error: any) {
      console.warn(`Failed to create investigation issue for ${investigationKey}: ${error.message ?? error}`)
    }

    // Rate limit: wait between issue creations
    await new Promise((resolve) => setTimeout(resolve, 2000))
  }

  // Save updated state
  await updateState((s) => {
    s.meta ??= {}
    s.meta.postedInvestigations = postedInvestigations
  })
}
